from .player import CREATE_TABLE as CREATE_PLAYERS, TABLE_NAME as PLAYERS_TABLE
from .session import CREATE_TABLE as CREATE_SESSIONS, TABLE_NAME as SESSIONS_TABLE
from .member import CREATE_TABLE as CREATE_MEMBERS, TABLE_NAME as MEMBERS_TABLE
from .character import CREATE_TABLE as CREATE_CHARACTERS, TABLE_NAME as CHARACTERS_TABLE
from .npc import CREATE_TABLE as CREATE_NPCS, TABLE_NAME as NPCS_TABLE
from .location import CREATE_TABLE as CREATE_LOCATIONS, TABLE_NAME as LOCATIONS_TABLE
from .session_history import CREATE_TABLE as CREATE_SESSION_HISTORY, TABLE_NAME as SESSION_HISTORY_TABLE
from .inventory import CREATE_TABLE as CREATE_INVENTORY, TABLE_NAME as INVENTORY_TABLE
from .global_history import CREATE_TABLE as CREATE_GLOBAL_HISTORY, TABLE_NAME as GLOBAL_HISTORY_TABLE

__all__ = [
    'CREATE_PLAYERS', 'PLAYERS_TABLE',
    'CREATE_SESSIONS', 'SESSIONS_TABLE',
    'CREATE_MEMBERS', 'MEMBERS_TABLE',
    'CREATE_CHARACTERS', 'CHARACTERS_TABLE',
    'CREATE_NPCS', 'NPCS_TABLE',
    'CREATE_LOCATIONS', 'LOCATIONS_TABLE',
    'CREATE_SESSION_HISTORY', 'SESSION_HISTORY_TABLE',
    'CREATE_INVENTORY', 'INVENTORY_TABLE',
    'CREATE_GLOBAL_HISTORY', 'GLOBAL_HISTORY_TABLE',
]